urls.py
from django.urls import path
from . import views

app_name = "adminPanel"


urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#adminpart url 
    path('dashboardcountry', views.dashboard_country, name='dashboardCountry'),
    path('deletecountry/<int:id>', views.delete_country, name='deleteCountry'),
    path('addcountry', views.add_country, name='addCountry'),
    path('dashboardcities/<int:id>', views.dashboard_city, name='dashboardCities'),
    path('dashboardcityadd', views.dashboard_city_add, name='dashboardCityAdd'),
    path('dashboardcitysingle/<int:id>', views.dashboard_city_single, name='dashboardCitySingle'),
    path('dashboardcitydelete/<int:id>', views.dashboard_city_delete, name='dashboardCityDelete'),

    path('dashboardfooter', views.dashboard_footer, name='dashboardFooter'),

    path('dashboardtermsandconditions', views.dashboard_terms_and_conditions, name='dashboardTermsAndConditions'),

    path('dasbhoardprivacypolicy', views.dashboard_privacy_policy, name='dashboardPrivacyPolicy'),

    path('packduration', views.dashboard_themed_pack_durations, name='packDuration'),
    path('addpackduration', views.dashboard_add_themed_pack_durations, name='AddpackDuration'),
    path('deletepackduration/<int:id>', views.delete_duration, name='deletePackDuration'),

    path('packvarieties', views.dashboard_pack_varieties, name='packVarieties'),
    path('packvarietiesadd', views.dashboard_add_pack_varieties, name='packVarietiesAdd'),
    path('deletevarieties/<int:id>', views.delete_variety, name='deleteVarieties'),

    path('dashboardcarmarks', views.dashboard_car_marks, name='dashboardCarMarks'),
    path('dashboardcarmarkadd', views.dashboard_car_mark_add, name='dashboardCarMarkAdd'),
    path('deletecarmark/<int:id>', views.delete_car_mark, name='deleteCarMark'),

    path('dashboarddefaultprice', views.dashboard_default_price, name='dashboardDefaultPrice'),
    path('dashboarddefaultpercentage', views.dashboard_default_percentage, name='dashboardDefaultPercentage'),
    path('dashboarddefaultpercentageadd', views.dashboard_default_percentage_add, name='dashboardDefaultPercentageAdd'),
    path('dashboarddefaultpercentageadd/<int:id>', views.dashboard_default_percentage_delete, name='dashboardDefaultPercentageDelete'),

    path('dashboardwhyus', views.dashboard_why_us, name='dashboardWhyUs'),
    path('dashboardwhyusadd', views.dashboard_why_us_add, name='dashboardWhyUsAdd'),
    path('dashboardwhyusedit/<int:id>', views.dashboard_why_us_edit, name='dashboardWhyUsEdit'),
#adminpart end

#user url

    path('admins', views.dashboard_admins, name='admins'),
    path('suppliers', views.dashboard_suppliers, name='suppliers'),
    path('customers', views.dashboard_customers, name='customers'),

    path('addadmin', views.dashboard_admin_add, name='addAdmin'),
    path('editadmin/<int:id>', views.dashboard_admin_edit, name="editAdmin"),
    path('editsupplier/<int:id>', views.dashboard_supplier_edit, name='editSupplier'),
    path('editcustomer/<int:id>', views.dashboard_customer_edit, name='editCustomer'),
    path('deleteadmin/<int:id>', views.delete_admin, name='deleteAdmin'),

#user end

#components

    path('dashboardfaq', views.dashboard_faq, name='dashboardFaq'),
    path('editfaq/<int:id>', views.faq_edit, name='editFaq'),
    path('deletefaq/<int:id>',views.faq_delete, name='deleteFaq'),
    path('addfaq',views.faq_add,name='addFaq'),

    path('homepagedestination', views.home_page_destination, name='homePageDestination'),

    path('interestingfacts', views.interesting_facts, name='interestingFacts'),
    path('editleftinterestingfact', views.edit_interesting_fact_left, name='editInterestingFactLeft'),
    path('editrightinteresingfact', views.edit_interesting_fact_right, name='editInterestingFactRight'),

    path('dashboardcontacts', views.dashboard_contacts, name='dashboardContacts'),
    path('dashboardcontact/<int:id>', views.dashboard_contact, name='dashboardContact'),

    path('dashboardabout', views.dashboard_about, name='dashboardAbout'),

#components end

    path('dashboardpacks', views.dashboard_themed_packs, name='dashboardPacks'),
    path('dashboardsinglepack/<int:id>', views.dashboard_single_pack, name='dashboardSinglePack'),
    path('editpack/<int:id>', views.edit_themed_pack, name='editPack'),
    path('editpackdescription/<int:id>/<int:findex>', views.edit_themed_pack_description, name='editPackDescription'),
    path('addpack', views.add_themed_pack, name='addPack'),
    path('addthemeddaysdescriptions/<int:id>', views.add_themed_days_descriptions, name='addThemedDaysDescriptions'),
    path('themedpackreservation/<int:id>', views.themed_pack_reservation, name='themedPackReservation'),

    path('priceedit/<int:id>', views.dashboard_price_edit, name='priceEdit'),
    path('quantityedit/<int:id>', views.dashboard_quantity_edit, name='quantityEdit'),

    path('themedpackreview', views.themed_pack_review, name='themedPackReview'),
    path('editthemedpackreview/<int:id>', views.edit_themed_pack_review, name='editThemedPackReview'),
    path('deletethemedpackreview/<int:id>', views.themed_pack_review_delete, name='deleteThemedPackReview'),

    path('themedpackorder', views.themed_pack_orders, name='themedPackOrder'),
    path('addthemedpackorder', views.themed_pack_order_add, name='addThemedPackOrder'),
    path('editthemedpackorder/<int:id>', views.themed_pack_order_edit, name='editThemedPackOrder'),

    path('dashboardapartment', views.dashboard_apartments, name='dashboardApartment'),
    path('dashboardapartmentsingle/<int:id>', views.dashboard_apartment_single, name='dashboardApartmentSingle'),
    path('dashboardaccommodationapartmentedit<int:id>', views.dashboard_accommodation_apartment_edit, name='dashboardAccommodationApartmentEdit'),
    path('dashboardapartmentedit<int:id>', views.dashboard_apartment_edit, name='dashboardApartmentEdit'),

    path('dashboardhotels', views.dashboard_hotels, name='dashboardHotels'),
    path('dashboardhotelsingle/<int:id>', views.dashboard_hotel_single, name='dashboardHotelSingle'),
    path('dashboardhoteledit<int:id>', views.dashboard_hotel_edit, name='dashboardHotelEdit'),
    path('dashboardhoteldelete/<int:id>', views.dashboard_hotel_delete, name='dashboardHotelDelete'),

    path('dashboardaccomodationadd', views.dashboard_accomodation_add, name='dashboardAccomodationAdd'),
    path('dashboardhoteladd/<int:id>', views.dashboard_hotel_add, name='dashboardHotelAdd'),
    path('dashboardhoteldescriptionadd/<int:id>', views.dashboard_hotel_description_add, name='dashboardHotelDescriptionAdd'),
    path('dashboardapartmentadd/<int:id>', views.dashboard_apartment_add, name='dashboardApartmentAdd'),


    path('accomodationreview', views.dashboard_accomodation_reviews, name='accomodationReview'),
    path('accomodationreviewedit/<int:id>', views.dashboard_accomodation_review_edit, name='accomodationReviewEdit'),

    path('carreview', views.dashboard_car_review, name='carReview'),
    path('carreviewedit/<int:id>', views.dashboard_car_review_edit, name='carReviewEdit'),
    path('carreviewdelete<int:id>', views.delete_car_review, name='carReviewDelete'),

    path('dashboardcars', views.dashboard_cars, name='dashboardCars'),
    path('dashboardcaradd', views.dashboard_car_add, name='dashboardCarAdd'),
    path('dashboardcaredit/<int:id>', views.dashboard_car_edit, name='dashboardCarEdit'),


]

templates/adminPanel/dashboardAccomodation/accomodation_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
 <!-- Begin Page Content -->
 <div class="main_pack">
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">change Accomodation</h1>
                    </div>

                 

               
<div class="acomodationSubPage">
    <form action="{% url 'adminPanel:dashboardAccomodationAdd' %}" class="form-group container-fluid" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
            <div class="contentalladd">
                <table class="table">
                    <thead>
                        <tr>
                            <div class="row align-items-center change_username">
                                <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                    {{ form }}
                                </div>
                            </div>
                        </tr>
                    </thead>
                </table>
            </div>

        <div class="row  save_Delete">
                            
            <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>
   
        </div>

    </form>

</div>
                          
                   



                        </div> <!-- 		End of Container -->

                                    </div>
                 

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}

templates/adminPanel/dashboardAccomodation/accomodation_review_edit.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Edit Accomodation review</h1>
                    </div>




                    <!---------------------- change themed pack review--------------------------------------------> 
                <form method="POST" action="{% url 'adminPanel:accomodationReviewEdit' accomodation_review.id %}">
                    {% csrf_token %}
                    <div class="contentalladd carpack">

                        <table>
                            <thead>
                                <tr>
                                    <div class="row align-items-center change_username">
                                        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                            {{ form }}
                                        </div>
                                    </div>
                                </tr>
                            </thead>
                        </table>

                        <div class="row  save_Delete">
                            
                            <button type="submit" class="save button_inner ">SAVE</button>
                           
                            <button type="button" class="Delete2  button_inner">Delete</button>
    
    
                </div>
                
            </form>


                        <!----------------------END themed pack review---------------------------------------------> 

                        

                        
                    




                    

                        </div> <!-- 		End of Container -->

                                    </div>
                 <!---------------------------------------------------------------------------------------->

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}

templates/adminPanel/dashboardAccomodation/accomodation_reviews.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}


                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Accomodation Reviews</h1>

                    </div>


                    <!-------------------THEMED PACK REVIEW---------------------------> 
                    
                    <table class="table " id= "table-id">
                        <div class="row">
                      <thead>
                          <tr>
                              <th style="width: 35px;">
                                  <input type="checkbox" class="checkAll" name="checkAll" />
                              </th>
                              <th class="AcomodationHeader">Accomodation Reviews</th> 
                              <th ></th> 
                              <th ></th> 
                            </tr>
   
                      </thead>
  
                      <tbody >
                        {% for review in dashboard_accomodation %}
                            {% if review.id in accomodation_review_notification_tuple %}
                              <tr>
                                  <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                    <td class="new_class"><a href="{% url 'adminPanel:accomodationReviewEdit' review.id %}">{{ review.accommodation }} | {{ review.user }}</a>
                                        <span class="new_inner" > NEW</span></td>
                                    
                                    <td> <a href="{% url 'adminPanel:accomodationReviewEdit' review.id %}">Edit </a> </td>
                                    <td class="" > <a href="">Delete Items </a> </td>
                                    <td></td>
                              </tr>
                                {% else %}
                                <tr>
                                    <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                      <td class=""><a href="{% url 'adminPanel:accomodationReviewEdit' review.id %}">{{ review.accommodation }} | {{ review.user }}</a></td>
                                      <td> <a href="{% url 'adminPanel:accomodationReviewEdit' review.id %}">Edit </a> </td>
                                      <td class="delete confirmation" > <a href="">Delete Items </a> </td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                      </tbody>
                      </table>
                      


                            <!---------------- END THEMED PACK REVIEW----------------->

                        </div>       
                         <!-- 		End of Container -->

                </div>
            

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}

templates/adminPanel/dashboardAccomodation/apartments.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Apartments</h1>
                        <div class="add">
                            <a href="{% url 'adminPanel:dashboardAccomodationAdd' %}">Add Accomodation</a>
                        </div>
                    </div>

                 

                    <!-- Content Row -->
                  <div class="filters">
                    <select class  ="form-control" name="state" id="maxRows">
						 
						 
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="70">70</option>
                        <option value="100">100</option>
                        <option value="5000">Show ALL Rows</option>
                       </select>
                       <div class="tb_search">
                        <input type="text" id="search_input_all" onkeyup="FilterkeyWord_all_table()" placeholder="Search.." class="form-control">
                                </div>
                  </div>


<!------------------------------------------------------------------------------>
                  <table class="table " id= "table-id">
                      <div class="row">
                    <thead>
                        <tr>
                            <th style="width: 35px;">
                                <input type="checkbox" class="checkAll" name="checkAll" />
                            </th>
                            <th class="AcomodationHeader">Acomodation</th> 
                            <th ></th> 
                        </tr>
                    </thead>

                    <tbody >
                       {% for apartment in apartments %}
                            <tr>
                                <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                <td class=""><a href="{% url 'adminPanel:dashboardApartmentSingle' apartment.id %}">{{ apartment.name }}</a></td>
                                <td class="delete" > Delete Item</td>
                               
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                <!---------------------------------------------------------------------------->

                        <!--		Start Pagination -->
                        <div class='pagination-container'>
                            <nav>
                            <ul class="pagination">
                            <!--	Here the JS Function Will Add the Rows -->
                            </ul>
                            </nav>
                        </div>
                        <!-- <div class="rows_count">Showing 11 to 20 of 91 entries</div> -->

                        </div> <!-- 		End of Container -->

                                    </div>
                 

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}

templates/adminPanel/dashboardAccomodation/dashboard_apartment_single.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
                <!-- Begin Page Content -->
                <div class="main_pack">
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Apartament: {{ accomodation.name }}</h1>
                    </div>

                 

                    <!-- Content Row -->

<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardAccommodationApartmentEdit' accomodation.id %}" class="form-group container-fluid" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ accomodation_form }}
                            </div>         
                        </div>
                    </tr>
                </thead>
            </table>
        </div>

    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>

<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardApartmentEdit' accomodation.id %}" class="form-group container-fluid">
        {% csrf_token %}

        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ apartment_form }}
                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>



    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>
                          
                   
{% endblock %}

templates/adminPanel/dashboardAccomodation/dashboard_hotel_single.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'js/dist/js-booking-calendar.css' %}"/>
<script src="{% static 'js/dist/js-booking-calendar.js' %}"></script>
                <!-- Begin Page Content -->
                <div class="main_pack">
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Hotel: {{ accomodation.name }}</h1>
                    </div>

                    <!-- Content Row -->
<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardAccommodationApartmentEdit' accomodation.id %}" class="form-group container-fluid" enctype="multipart/form-data">
        {% csrf_token %}

        

        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ accomodation_form }}
                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>



    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>


<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardHotelEdit' accomodation.id %}" class="form-group container-fluid">
        {% csrf_token %}
        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ hotel_form }}
                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>

    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>

{% for key,value in hotel_room_dict.items %}
<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardApartmentEdit' accomodation.id %}" class="form-group container-fluid">
        {% csrf_token %}
        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ value }}
                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>

        
    <div class="row  save_Delete">                      
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>
    </div>

    </form>
    {% endfor %}
    <div class="col-md-4">
        <h6 class="calendar_title">Calendar Filter</h6>
    <form method='POST' action="{% url 'adminPanel:dashboardHotelSingle' accomodation.id %}#caledendar_input" id="caledendar_input">
        {% csrf_token %}
        <input id="test1" name='calendar_start_date' class="form-control" type="date" value="">
        <input id="test2" name='calendar_end_date' class="form-control" type="date" value="">
        <button type='submit' id="submitclick" class="btn btn-primary" >Send</button>
    </form>
    </div>

        <div class="gantt-target"></div>
  
</div>
{% for room, dates in calendar_rooms.items %}

{{ dates.0.0|date:"d-m-Y" }}
{{ dates.1.1|date:"d-m-Y" }}

{% endfor %}


<script>

    function initGantt(properties, init_scroll_position = null) {
        console.log('properties', properties);
        var gantt_chart = new Gantt(".gantt-target", properties, {

            on_click: function (task) {
                console.log(task);
            },
            on_date_change: function (task, start, end, scrollXPosition) {
                console.log(scrollXPosition);
            },
            on_progress_change: function (task, progress) {
                console.log(task, progress);
            },
            on_view_change: function (mode) {
                console.log(mode);
            },
            on_date_added: function (start, end, property, propertyIdx, xPosition, yPosition) {
                console.log('start', start);
                console.log('end', end);
                console.log('property', property);
                console.log('propertyIdx', propertyIdx);
                console.log('xPosition', xPosition);
                console.log('yPosition', yPosition);
                let props = properties;
                props[propertyIdx]['bookings'].push({
                    id: '100',
                    start: new date(),
                    end: "2022-01-01",
                    name: 'Foodddddddddddddddddd',
                    description: 'Beschreibung',
                })
                initGantt(props, xPosition)

            },
            view_mode: 'Day',
            language: 'en',
            start_date: '{{ calendar_start_date }}',
            end_date: "{{ calendar_end_date }}",
            show_label: true,
            bar_corner_radius: 0,
            column_width: 10,
            init_scroll_position: init_scroll_position,
            custom_click_on_bar: function (task) {
                console.log('custom_click_on_bar', task)
            }
        });
    }

    var properties = [ 
    {% for room, dates in calendar_rooms.items %}
        {
            name: '{{ room.room_number }}',

            bookings: [
            
                {
                    start: '{{ dates.0.0|date:"Y-m-d" }}',
                    end: '{{ dates.1.1|date:"Y-m-d" }}',
                    name: '',
                    description: 'Beschreibung',
                },
            
            
            ]
            
        },
        {% endfor %}
        
    ];

    initGantt(properties);
        let count=0
    let bar=document.querySelectorAll('.gantt .bar');
    bar.forEach(items=>{
        let colors = ['Aqua', 'Coral'];
        console.log(items)
        items.style.fill=colors[count];
        if(count<colors.length-1){
            count++
        }
        else{
            count=0
        }
    })
   
    </script>
                                     
{% endblock %}

templates/adminPanel/dashboardAccomodation/hotels.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Hotels</h1>
                        <div class="add">
                            <a href="{% url 'adminPanel:dashboardAccomodationAdd' %}">Add Accomodation</a>
                        </div>
                    </div>

                 

                    <!-- Content Row -->
                  <div class="filters">
                    <select class  ="form-control" name="state" id="maxRows">
						 
						 
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="70">70</option>
                        <option value="100">100</option>
                        <option value="5000">Show ALL Rows</option>
                       </select>
                       <div class="tb_search">
                        <input type="text" id="search_input_all" onkeyup="FilterkeyWord_all_table()" placeholder="Search.." class="form-control">
                                </div>
                  </div>


<!------------------------------------------------------------------------------>
                  <table class="table " id= "table-id">
                      <div class="row">
                    <thead>
                        <tr>
                            <th style="width: 35px;">
                                <input type="checkbox" class="checkAll" name="checkAll" />
                            </th>
                            <th class="AcomodationHeader">Acomodation</th> 
                            <th ></th> 
                        </tr>
                    </thead>
                    <tbody >
                       {% for hotel in hotels %}
                       
                            <tr>
                                <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                <td class=""><a href="{% url 'adminPanel:dashboardHotelSingle' hotel.id %}">{{ hotel.name }}</a></td>
                                <td class="delete confirmation" > <a href="{% url 'adminPanel:dashboardHotelDelete' hotel.id %}">Delete Items </a> </td>

                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                <!---------------------------------------------------------------------------->

                        <!--		Start Pagination -->
                        <div class='pagination-container'>
                            <nav>
                            <ul class="pagination">
                            <!--	Here the JS Function Will Add the Rows -->
                            </ul>
                            </nav>
                        </div>
                        <!-- <div class="rows_count">Showing 11 to 20 of 91 entries</div> -->

                        </div> <!-- 		End of Container -->

                                    </div>
                 

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}