urls.py
from django.urls import path
from . import views

app_name = "adminPanel"


urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#adminpart url 
    path('dashboardcountry', views.dashboard_country, name='dashboardCountry'),
    path('deletecountry/<int:id>', views.delete_country, name='deleteCountry'),
    path('addcountry', views.add_country, name='addCountry'),
    path('dashboardcities/<int:id>', views.dashboard_city, name='dashboardCities'),
    path('dashboardcityadd', views.dashboard_city_add, name='dashboardCityAdd'),
    path('dashboardcitysingle/<int:id>', views.dashboard_city_single, name='dashboardCitySingle'),
    path('dashboardcitydelete/<int:id>', views.dashboard_city_delete, name='dashboardCityDelete'),

    path('dashboardfooter', views.dashboard_footer, name='dashboardFooter'),

    path('dashboardtermsandconditions', views.dashboard_terms_and_conditions, name='dashboardTermsAndConditions'),

    path('dasbhoardprivacypolicy', views.dashboard_privacy_policy, name='dashboardPrivacyPolicy'),

    path('packduration', views.dashboard_themed_pack_durations, name='packDuration'),
    path('addpackduration', views.dashboard_add_themed_pack_durations, name='AddpackDuration'),
    path('deletepackduration/<int:id>', views.delete_duration, name='deletePackDuration'),

    path('packvarieties', views.dashboard_pack_varieties, name='packVarieties'),
    path('packvarietiesadd', views.dashboard_add_pack_varieties, name='packVarietiesAdd'),
    path('deletevarieties/<int:id>', views.delete_variety, name='deleteVarieties'),

    path('dashboardcarmarks', views.dashboard_car_marks, name='dashboardCarMarks'),
    path('dashboardcarmarkadd', views.dashboard_car_mark_add, name='dashboardCarMarkAdd'),
    path('deletecarmark/<int:id>', views.delete_car_mark, name='deleteCarMark'),

    path('dashboarddefaultprice', views.dashboard_default_price, name='dashboardDefaultPrice'),
    path('dashboarddefaultpercentage', views.dashboard_default_percentage, name='dashboardDefaultPercentage'),
    path('dashboarddefaultpercentageadd', views.dashboard_default_percentage_add, name='dashboardDefaultPercentageAdd'),
    path('dashboarddefaultpercentageadd/<int:id>', views.dashboard_default_percentage_delete, name='dashboardDefaultPercentageDelete'),

    path('dashboardwhyus', views.dashboard_why_us, name='dashboardWhyUs'),
    path('dashboardwhyusadd', views.dashboard_why_us_add, name='dashboardWhyUsAdd'),
    path('dashboardwhyusedit/<int:id>', views.dashboard_why_us_edit, name='dashboardWhyUsEdit'),
#adminpart end

#user url

    path('admins', views.dashboard_admins, name='admins'),
    path('suppliers', views.dashboard_suppliers, name='suppliers'),
    path('customers', views.dashboard_customers, name='customers'),

    path('addadmin', views.dashboard_admin_add, name='addAdmin'),
    path('editadmin/<int:id>', views.dashboard_admin_edit, name="editAdmin"),
    path('editsupplier/<int:id>', views.dashboard_supplier_edit, name='editSupplier'),
    path('editcustomer/<int:id>', views.dashboard_customer_edit, name='editCustomer'),
    path('deleteadmin/<int:id>', views.delete_admin, name='deleteAdmin'),

#user end

#components

    path('dashboardfaq', views.dashboard_faq, name='dashboardFaq'),
    path('editfaq/<int:id>', views.faq_edit, name='editFaq'),
    path('deletefaq/<int:id>',views.faq_delete, name='deleteFaq'),
    path('addfaq',views.faq_add,name='addFaq'),

    path('homepagedestination', views.home_page_destination, name='homePageDestination'),

    path('interestingfacts', views.interesting_facts, name='interestingFacts'),
    path('editleftinterestingfact', views.edit_interesting_fact_left, name='editInterestingFactLeft'),
    path('editrightinteresingfact', views.edit_interesting_fact_right, name='editInterestingFactRight'),

    path('dashboardcontacts', views.dashboard_contacts, name='dashboardContacts'),
    path('dashboardcontact/<int:id>', views.dashboard_contact, name='dashboardContact'),

    path('dashboardabout', views.dashboard_about, name='dashboardAbout'),

#components end

    path('dashboardpacks', views.dashboard_themed_packs, name='dashboardPacks'),
    path('dashboardsinglepack/<int:id>', views.dashboard_single_pack, name='dashboardSinglePack'),
    path('editpack/<int:id>', views.edit_themed_pack, name='editPack'),
    path('editpackdescription/<int:id>/<int:findex>', views.edit_themed_pack_description, name='editPackDescription'),
    path('addpack', views.add_themed_pack, name='addPack'),
    path('addthemeddaysdescriptions/<int:id>', views.add_themed_days_descriptions, name='addThemedDaysDescriptions'),
    path('themedpackreservation/<int:id>', views.themed_pack_reservation, name='themedPackReservation'),

    path('priceedit/<int:id>', views.dashboard_price_edit, name='priceEdit'),
    path('quantityedit/<int:id>', views.dashboard_quantity_edit, name='quantityEdit'),

    path('themedpackreview', views.themed_pack_review, name='themedPackReview'),
    path('editthemedpackreview/<int:id>', views.edit_themed_pack_review, name='editThemedPackReview'),
    path('deletethemedpackreview/<int:id>', views.themed_pack_review_delete, name='deleteThemedPackReview'),

    path('themedpackorder', views.themed_pack_orders, name='themedPackOrder'),
    path('addthemedpackorder', views.themed_pack_order_add, name='addThemedPackOrder'),
    path('editthemedpackorder/<int:id>', views.themed_pack_order_edit, name='editThemedPackOrder'),

    path('dashboardapartment', views.dashboard_apartments, name='dashboardApartment'),
    path('dashboardapartmentsingle/<int:id>', views.dashboard_apartment_single, name='dashboardApartmentSingle'),
    path('dashboardaccommodationapartmentedit<int:id>', views.dashboard_accommodation_apartment_edit, name='dashboardAccommodationApartmentEdit'),
    path('dashboardapartmentedit<int:id>', views.dashboard_apartment_edit, name='dashboardApartmentEdit'),

    path('dashboardhotels', views.dashboard_hotels, name='dashboardHotels'),
    path('dashboardhotelsingle/<int:id>', views.dashboard_hotel_single, name='dashboardHotelSingle'),
    path('dashboardhoteledit<int:id>', views.dashboard_hotel_edit, name='dashboardHotelEdit'),
    path('dashboardhoteldelete/<int:id>', views.dashboard_hotel_delete, name='dashboardHotelDelete'),

    path('dashboardaccomodationadd', views.dashboard_accomodation_add, name='dashboardAccomodationAdd'),
    path('dashboardhoteladd/<int:id>', views.dashboard_hotel_add, name='dashboardHotelAdd'),
    path('dashboardhoteldescriptionadd/<int:id>', views.dashboard_hotel_description_add, name='dashboardHotelDescriptionAdd'),
    path('dashboardapartmentadd/<int:id>', views.dashboard_apartment_add, name='dashboardApartmentAdd'),


    path('accomodationreview', views.dashboard_accomodation_reviews, name='accomodationReview'),
    path('accomodationreviewedit/<int:id>', views.dashboard_accomodation_review_edit, name='accomodationReviewEdit'),

    path('carreview', views.dashboard_car_review, name='carReview'),
    path('carreviewedit/<int:id>', views.dashboard_car_review_edit, name='carReviewEdit'),
    path('carreviewdelete<int:id>', views.delete_car_review, name='carReviewDelete'),

    path('dashboardcars', views.dashboard_cars, name='dashboardCars'),
    path('dashboardcaradd', views.dashboard_car_add, name='dashboardCarAdd'),
    path('dashboardcaredit/<int:id>', views.dashboard_car_edit, name='dashboardCarEdit'),


]

templates/adminPanel/adminPart/Themedpackvarieties.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}


<div class="container-fluid">


    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Select themed pack variety to change</h1>
        <div class="add">
            <a href="{% url 'adminPanel:packVarietiesAdd' %}">Add Select themed pack variety</a>
        </div>
    </div>


    <table class="table" id= "table-id">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" class="checkAll" name="checkAll" />
                </th>
                <th >THEMED PACK VARIETY</th>
                <th ></th>
                <th ></th>
                
            </tr>
        </thead>

        <tbody>
            {% for variety in pack_variety %}
                <tr>
                    <td><input type="checkbox" name="item[]" value="1"></td>
                    <td colspan="2"><a href="">{{ variety.pack_variety }} </a></td>
                    <td class="delete confirmation"><a href="{% url 'adminPanel:deleteVarieties' variety.id %}" class="confirmation"> Delete</a> </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
                   

</div>

{% endblock %}

templates/adminPanel/adminPart/dashboard_Themed_pack_durations.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Select themed pack duration to change</h1>
        <div class="add">
            <a href="{% url 'adminPanel:AddpackDuration' %}">Add themed pack duration</a>
        </div>
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "table-id">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="checkAll" name="checkAll" />
            </th>
            <th >THEMED PACK DURATION</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for duration in pack_duration %}
            <tr>
                <td><input type="checkbox" name="item[]" value="1"></td>
                <td colspan="2"><a href=""> {{ duration.duration }} </a></td>
                <td class="delete confirmation"><a href="{% url 'adminPanel:deletePackDuration' duration.id %}">Delete</a> </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}

templates/adminPanel/adminPart/dashboard_Themed_pack_varieties_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add themed pack variety</h1>
            
        </div>
            <form method="POST" action="{% url 'adminPanel:packVarietiesAdd' %}">
                    {% csrf_token %}
                    
                <table class="table" id="add" >
                    <thead>
                        <tr>
                            
                            
                            <th >
                                {{ form }}
                            </th>
                            
                            
                        </tr>
                    </thead>
                    
                    </table>

                    <div class="row  save_Delete">

                    <button type="submit" class="save button_inner ">SAVE</button>

                </div>

            </form>
                          
     </div>

</div>
                 
{% endblock %}

templates/adminPanel/adminPart/dashboard_car_mark_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Car Mark</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardCarMarkAdd' %}">
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

templates/adminPanel/adminPart/dashboard_car_marks.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Car Marks</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardCarMarkAdd' %}">Add Car Mark</a>
        </div>
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "table-id">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="checkAll" name="checkAll" />
            </th>
            <th >Car Marks</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for car in car_marks %}
            <tr>
                <td><input type="checkbox" name="item[]" value="1"></td>
                <td colspan="2"><a href=""> {{ car.car_mark }} </a></td>
                <td class="delete confirmation"><a href="{% url 'adminPanel:deleteCarMark' car.id %}">Delete</a> </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}

templates/adminPanel/adminPart/dashboard_cities.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Select City To Change</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardCityAdd' %}">Add City</a>
        </div>
    </div>

    

    <!-- Content Row -->
        <table class="table" id= "table-id">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" class="checkAll" name="checkAll" />
                </th>
                <th >Country</th>
                <th ></th>
                <th ></th>
                
            </tr>
        </thead>
        <tbody>
            {% for city in cities %}
                <tr>
                    <td><input type="checkbox" name="item[]" value="1"></td>
                    <td colspan="2"><a href="{% url 'adminPanel:dashboardCitySingle' city.id %}"> {{ city.city }} </a></td>
                    <td class="delete"><a href="{% url 'adminPanel:dashboardCityDelete' city.id %}" class="confirmation"> Delete Country</a> </td>

                </tr>
            {% endfor %}
    
        </tbody>
    </table>
    

        <!--		Start Pagination -->
        <div class='pagination-container'>
            <nav>
            <ul class="pagination">
            <!--	Here the JS Function Will Add the Rows -->
            </ul>
            </nav>
        </div>
        <!-- <div class="rows_count">Showing 11 to 20 of 91 entries</div> -->

        </div> <!-- 		End of Container -->

                    </div>
    


<!-- /.container-fluid -->


<!-- End of Main Content -->

{% endblock %}

templates/adminPanel/adminPart/dashboard_city_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add City</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardCityAdd' %}" enctype="multipart/form-data">
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
                <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

<div id="cities" style="display: none;">{{ js_cities }} </div>


<script>
    let cities=document.getElementById('cities').innerHTML;
    console.log(cities)
   let k=cities.split(',');
   console.log(k)
   function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}
autocomplete(document.getElementById("map_input"), k);

</script>
{% endblock %}

templates/adminPanel/adminPart/dashboard_city_single.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.css"/>
  <link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.css"/>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>

        <div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">City: {{ city.city }}</h1>
                    </div>
                    <!---------------------- change themed pack--------------------------------------------> 
            <form method="POST" action="{% url 'adminPanel:dashboardCitySingle' city.id %}">
                {% csrf_token %}
                <div class="contentalladd">
                        <table class="table">
                            <thead>
                                <tr>
                                    <div class="row align-items-center change_username">
                                        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
            
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-10">
                                            {{ form }}
                                        </div>
                                    </div>
                                </tr>
                            </thead>
                        </table>
    
                        <div class="row  save_Delete">
                            
                                <button type="submit" class="save button_inner ">SAVE</button>
                       
                        </div>
    
    
                </div>
            </form>

{% endblock %}

templates/adminPanel/adminPart/dashboard_default_percentage.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Default Percentages</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardDefaultPercentageAdd' %}">Add Default Percentage</a>
        </div>
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="checkAll" name="checkAll" />
            </th>
            <th >Supplier</th>
            <th >Percentage</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for percentage in percentages %}
            <tr>
                <td><input type="checkbox" name="item[]" value="1"></td>
                <td colspan=""><a href=""> {{ percentage.supplier.email }} </a></td>
                <td colspan=""><a href=""> {{ percentage.percentage }}% </a></td>
                <td class="delete confirmation"><a href="{% url 'adminPanel:dashboardDefaultPercentageDelete' percentage.id %}">Delete</a> </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}

templates/adminPanel/adminPart/dashboard_default_percentage_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Default Percentage</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardDefaultPercentageAdd' %}">
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

templates/adminPanel/adminPart/dashboard_default_price.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Default Price</h1>

                    </div>

                   
                    <form action="{% url 'adminPanel:dashboardDefaultPrice' %}" method="POST">
                        
                    {% csrf_token %}

                     
                    <table class="table" id="" >
                        
                            <tr>
                                
                                <th style="width: 25%;" ></th>
                                <td >                                  
                                    {{ form }}
                                 </td>                             
                               
                            </tr>
                            
                     </table>
                     
                    <div class="row  save_Delete">

                        <button type="submit" class="save button_inner ">SAVE</button>
                    
                    </div>
                     
                    </form>

        
                  
                        </div> <!-- 		End of Container -->

                                    </div>
                 

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

 {% endblock %}

templates/adminPanel/adminPart/dashboard_privacy_policy.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<script src="https://cdn.ckeditor.com/ckeditor5/11.0.1/classic/ckeditor.js"></script>
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Privacy Policy</h1>

                    </div>
           

                    <form action="{% url 'adminPanel:dashboardPrivacyPolicy' %}" method="POST">
                        
                    {% csrf_token %}

                     
                    <table class="table table_terms" id="" >
                        
                            <tr>
                                
                               
                                <td >                                  
                                    {{ form.text }}
                                 </td>                             
                               
                            </tr>
                            
                     </table>
                     
                    <div class="row  save_Delete">

                        <button type="submit" class="save button_inner ">SAVE</button>
                    
                    </div>
                     
                    </form>

        
                  
                        </div> <!-- 		End of Container -->

                                    </div>
                 

                                    <script>
                                        ClassicEditor
                                            .create( document.querySelector( '#editor' ) )
                                            .catch( error => {
                                                console.error( error );
                                            } );
                                    </script>
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

 {% endblock %}

templates/adminPanel/adminPart/dashboard_why_us.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Why Us</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardWhyUsAdd' %}">Add Why Us</a>
        </div>
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "table-id">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="checkAll" name="checkAll" />
            </th>
            <th >Why Us</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for us in why_us %}
            <tr>
                <td><input type="checkbox" name="item[]" value="1"></td>
                <td colspan="2"><a href="{% url 'adminPanel:dashboardWhyUsEdit' us.id %}"> {{ us.title }} </a></td>
                <td class="delete confirmation"><a href="">Delete</a> </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}