urls.py
from django.urls import path
from . import views

app_name = "adminPanel"


urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#adminpart url 
    path('dashboardcountry', views.dashboard_country, name='dashboardCountry'),
    path('deletecountry/<int:id>', views.delete_country, name='deleteCountry'),
    path('addcountry', views.add_country, name='addCountry'),
    path('dashboardcities/<int:id>', views.dashboard_city, name='dashboardCities'),
    path('dashboardcityadd', views.dashboard_city_add, name='dashboardCityAdd'),
    path('dashboardcitysingle/<int:id>', views.dashboard_city_single, name='dashboardCitySingle'),
    path('dashboardcitydelete/<int:id>', views.dashboard_city_delete, name='dashboardCityDelete'),

    path('dashboardfooter', views.dashboard_footer, name='dashboardFooter'),

    path('dashboardtermsandconditions', views.dashboard_terms_and_conditions, name='dashboardTermsAndConditions'),

    path('dasbhoardprivacypolicy', views.dashboard_privacy_policy, name='dashboardPrivacyPolicy'),

    path('packduration', views.dashboard_themed_pack_durations, name='packDuration'),
    path('addpackduration', views.dashboard_add_themed_pack_durations, name='AddpackDuration'),
    path('deletepackduration/<int:id>', views.delete_duration, name='deletePackDuration'),

    path('packvarieties', views.dashboard_pack_varieties, name='packVarieties'),
    path('packvarietiesadd', views.dashboard_add_pack_varieties, name='packVarietiesAdd'),
    path('deletevarieties/<int:id>', views.delete_variety, name='deleteVarieties'),

    path('dashboardcarmarks', views.dashboard_car_marks, name='dashboardCarMarks'),
    path('dashboardcarmarkadd', views.dashboard_car_mark_add, name='dashboardCarMarkAdd'),
    path('deletecarmark/<int:id>', views.delete_car_mark, name='deleteCarMark'),

    path('dashboarddefaultprice', views.dashboard_default_price, name='dashboardDefaultPrice'),
    path('dashboarddefaultpercentage', views.dashboard_default_percentage, name='dashboardDefaultPercentage'),
    path('dashboarddefaultpercentageadd', views.dashboard_default_percentage_add, name='dashboardDefaultPercentageAdd'),
    path('dashboarddefaultpercentageadd/<int:id>', views.dashboard_default_percentage_delete, name='dashboardDefaultPercentageDelete'),

    path('dashboardwhyus', views.dashboard_why_us, name='dashboardWhyUs'),
    path('dashboardwhyusadd', views.dashboard_why_us_add, name='dashboardWhyUsAdd'),
    path('dashboardwhyusedit/<int:id>', views.dashboard_why_us_edit, name='dashboardWhyUsEdit'),
#adminpart end

#user url

    path('admins', views.dashboard_admins, name='admins'),
    path('suppliers', views.dashboard_suppliers, name='suppliers'),
    path('customers', views.dashboard_customers, name='customers'),

    path('addadmin', views.dashboard_admin_add, name='addAdmin'),
    path('editadmin/<int:id>', views.dashboard_admin_edit, name="editAdmin"),
    path('editsupplier/<int:id>', views.dashboard_supplier_edit, name='editSupplier'),
    path('editcustomer/<int:id>', views.dashboard_customer_edit, name='editCustomer'),
    path('deleteadmin/<int:id>', views.delete_admin, name='deleteAdmin'),

#user end

#components

    path('dashboardfaq', views.dashboard_faq, name='dashboardFaq'),
    path('editfaq/<int:id>', views.faq_edit, name='editFaq'),
    path('deletefaq/<int:id>',views.faq_delete, name='deleteFaq'),
    path('addfaq',views.faq_add,name='addFaq'),

    path('homepagedestination', views.home_page_destination, name='homePageDestination'),

    path('interestingfacts', views.interesting_facts, name='interestingFacts'),
    path('editleftinterestingfact', views.edit_interesting_fact_left, name='editInterestingFactLeft'),
    path('editrightinteresingfact', views.edit_interesting_fact_right, name='editInterestingFactRight'),

    path('dashboardcontacts', views.dashboard_contacts, name='dashboardContacts'),
    path('dashboardcontact/<int:id>', views.dashboard_contact, name='dashboardContact'),

    path('dashboardabout', views.dashboard_about, name='dashboardAbout'),

#components end

    path('dashboardpacks', views.dashboard_themed_packs, name='dashboardPacks'),
    path('dashboardsinglepack/<int:id>', views.dashboard_single_pack, name='dashboardSinglePack'),
    path('editpack/<int:id>', views.edit_themed_pack, name='editPack'),
    path('editpackdescription/<int:id>/<int:findex>', views.edit_themed_pack_description, name='editPackDescription'),
    path('addpack', views.add_themed_pack, name='addPack'),
    path('addthemeddaysdescriptions/<int:id>', views.add_themed_days_descriptions, name='addThemedDaysDescriptions'),
    path('themedpackreservation/<int:id>', views.themed_pack_reservation, name='themedPackReservation'),

    path('priceedit/<int:id>', views.dashboard_price_edit, name='priceEdit'),
    path('quantityedit/<int:id>', views.dashboard_quantity_edit, name='quantityEdit'),

    path('themedpackreview', views.themed_pack_review, name='themedPackReview'),
    path('editthemedpackreview/<int:id>', views.edit_themed_pack_review, name='editThemedPackReview'),
    path('deletethemedpackreview/<int:id>', views.themed_pack_review_delete, name='deleteThemedPackReview'),

    path('themedpackorder', views.themed_pack_orders, name='themedPackOrder'),
    path('addthemedpackorder', views.themed_pack_order_add, name='addThemedPackOrder'),
    path('editthemedpackorder/<int:id>', views.themed_pack_order_edit, name='editThemedPackOrder'),

    path('dashboardapartment', views.dashboard_apartments, name='dashboardApartment'),
    path('dashboardapartmentsingle/<int:id>', views.dashboard_apartment_single, name='dashboardApartmentSingle'),
    path('dashboardaccommodationapartmentedit<int:id>', views.dashboard_accommodation_apartment_edit, name='dashboardAccommodationApartmentEdit'),
    path('dashboardapartmentedit<int:id>', views.dashboard_apartment_edit, name='dashboardApartmentEdit'),

    path('dashboardhotels', views.dashboard_hotels, name='dashboardHotels'),
    path('dashboardhotelsingle/<int:id>', views.dashboard_hotel_single, name='dashboardHotelSingle'),
    path('dashboardhoteledit<int:id>', views.dashboard_hotel_edit, name='dashboardHotelEdit'),
    path('dashboardhoteldelete/<int:id>', views.dashboard_hotel_delete, name='dashboardHotelDelete'),

    path('dashboardaccomodationadd', views.dashboard_accomodation_add, name='dashboardAccomodationAdd'),
    path('dashboardhoteladd/<int:id>', views.dashboard_hotel_add, name='dashboardHotelAdd'),
    path('dashboardhoteldescriptionadd/<int:id>', views.dashboard_hotel_description_add, name='dashboardHotelDescriptionAdd'),
    path('dashboardapartmentadd/<int:id>', views.dashboard_apartment_add, name='dashboardApartmentAdd'),


    path('accomodationreview', views.dashboard_accomodation_reviews, name='accomodationReview'),
    path('accomodationreviewedit/<int:id>', views.dashboard_accomodation_review_edit, name='accomodationReviewEdit'),

    path('carreview', views.dashboard_car_review, name='carReview'),
    path('carreviewedit/<int:id>', views.dashboard_car_review_edit, name='carReviewEdit'),
    path('carreviewdelete<int:id>', views.delete_car_review, name='carReviewDelete'),

    path('dashboardcars', views.dashboard_cars, name='dashboardCars'),
    path('dashboardcaradd', views.dashboard_car_add, name='dashboardCarAdd'),
    path('dashboardcaredit/<int:id>', views.dashboard_car_edit, name='dashboardCarEdit'),


]

templates/adminPanel/dashboardThemedTours/Themed_Pack.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Themed Packs</h1>
                        <div class="add">
                            <a href="{% url 'adminPanel:addPack' %}">ADD THEMED PACK</a>
                        </div>
                    </div>

                    <div class="filters">
                        <select class  ="form-control" name="state" id="maxRows">
                             
                             
                            <option value="10">10</option>
                            <option value="15">15</option>
                            <option value="20">20</option>
                            <option value="50">50</option>
                            <option value="70">70</option>
                            <option value="100">100</option>
                            <option value="5000">Show ALL Rows</option>
                           </select>
                           <div class="tb_search">
                            <input type="text" id="search_input_all" onkeyup="FilterkeyWord_all_table()" placeholder="Search.." class="form-control">
                                    </div>
                      </div>
                    <!-------------------Themed pack---------------------------> 


                    <table class="table " id= "table-id">
                        <div class="row">
                      <thead>
                          <tr>
                              <th style="width: 35px;">
                                  <input type="checkbox" class="checkAll" name="checkAll" />
                              </th>
                              <th class="AcomodationHeader">THEMED PACK</th> 
                              <th ></th> 
                          </tr>
                      </thead>


  
                      <tbody >
                         {% for pack in packs %}
                              <tr>
                                  <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                    <td class=""><a href="{% url 'adminPanel:dashboardSinglePack' pack.id %}">{{ pack.pack_name }} | {{ pack.trip_variety }}</a></td>
                                    <td class="delete" > <a href="">Delete Items</a>  </td>
                                 
                              </tr>
                        {% endfor %}
                      </tbody>
                      </table>



                            <!---------------- END Themed pack----------------->

                        </div>       
                         <!-- 		End of Container -->

                </div>
            

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}






templates/adminPanel/dashboardThemedTours/Themed_Pack_Reviews.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}


                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Themed Packs Reviews</h1>

                    </div>
                    <div class="filters">
                        <select class  ="form-control review_filter" name="state" id="select" onchange="myFunction()">>
                            {% for pack in packs %}
                            <option value="{{ pack }}">{{ pack }}</option>
                            {% endfor %}
                           </select>
                           <div class="tb_search">
                            <input type="text" id="search_input_all" onkeyup="FilterkeyWord_all_table()" placeholder="Search.." class="form-control">
                            </div>
                      </div>

                    <!-------------------THEMED PACK REVIEW---------------------------> 
                    
                    <table class="table " id= "table-id">
                        <div class="row">
                      <thead>
                          <tr>
                              <th style="width: 35px;">
                                  <input type="checkbox" class="checkAll" name="checkAll" />
                              </th>
                              <th class="AcomodationHeader">Themed Pack Reviews</th> 
                              <th ></th> 
                              <th ></th> 
                            </tr>
   
                      </thead>
  
                      <tbody >
                        {% for pack_review in themed_pack_reviews %}
                            {% if pack_review.id in themed_pack_review_notification_tuple %}
                              <tr>
                                  <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                    <td class="new_class"><a href="{% url 'adminPanel:editThemedPackReview' pack_review.id %}">{{ pack_review.pack }} | {{ pack_review.user }}</a>
                                        <span class="new_inner" > NEW</span></td>
                                    
                                    <td> <a href="{% url 'adminPanel:editThemedPackReview' pack_review.id %}">Edit </a> </td>
                                    <td class="delete" > <a href="{% url 'adminPanel:deleteThemedPackReview' pack_review.id %}">Delete Item</a> </td>
                                    <td></td>
                              </tr>
                                {% else %}
                                <tr>
                                    <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                      <td class=""><a href="{% url 'adminPanel:editThemedPackReview' pack_review.id %}">{{ pack_review.pack }} | {{ pack_review.user }}</a></td>
                                      <td> <a href="{% url 'adminPanel:editThemedPackReview' pack_review.id %}">Edit </a> </td>
                                      <td class="delete confirmation" > <a href="{% url 'adminPanel:deleteThemedPackReview' pack_review.id %}">Delete Item</a> </td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                      </tbody>
                      </table>
                      


                            <!---------------- END THEMED PACK REVIEW----------------->

                        </div>       
                         <!-- 		End of Container -->

                </div>
            

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}





templates/adminPanel/dashboardThemedTours/addThemedDaysDescriptions.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

<form action="{% url 'adminPanel:addThemedDaysDescriptions' pack.id %}" id="forms" method="POST">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}

        <div id="form_inner">
            <div class="col-2">
                <label>{{ form.description.label }} - Day {{ forloop.counter }}</label>
            </div>
            <div class="col-6 themedescription">
                <div class="input-group">
                    {{ form.description }}
                </div>
            </div>
        </div>


        {% endfor %}


     <div class="row col-6 themedescription_button ">
         <button type="submit" class="save button_inner ">submit</button>
     </div>
    </form>
{% endblock %}

templates/adminPanel/dashboardThemedTours/add_Themed_Pack.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
{% load countries %}

<div class="main_pack">
<div class="container-fluid">
    <!----------------------------------------------------------------------------------->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">add themed pack</h1>

    </div>




                    <!---------------------- ADD themed pack--------------------------------------------> 
    <form action="{% url 'adminPanel:addPack' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="contentalladd pack">

                <table>
                    <thead>

                            <div class="row align-items-center change_username">
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-10">
                                    {{ form }}
                                </div>
                            </div>

                    </thead>
                </table>

                <div class="row  save_Delete">
                        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>
                </div>

        </div>
    </form>

</div> 

{% endblock %}






templates/adminPanel/dashboardThemedTours/edit_themed_pack.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
{% load countries %}
{% load index %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.css"/>
  <link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.css"/>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>


        <div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Edit Themed Pack</h1>
                        <div class="gotodc" id="goscrol" >
                            <a class="save button_inner "  href="#goscrol1">Go descriptions
                            </a>
                            <a class="save button_inner " href="#calendar">Go calendar
                            </a>
                        </div>
                    </div>

            <form method="POST" action="{% url 'adminPanel:editPack' pack.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="contentalladd">
                        <table class="table">
                            <thead>
                                <tr>
                                    <div class="row align-items-center change_username">
                                        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
            
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-10">
                                            {{ form }}
                                        </div>
                                    </div>
                                </tr>
                            </thead>
                        </table>
    
                        <div class="row  save_Delete">
                            
                                <button type="submit" class="save button_inner ">SAVE</button>
                       
                              <button type="button" class="Delete2  button_inner">Delete</button>
                            
                          </div>
    
    
                </div>
            </form>

            <!-- Themed pack days description -->
            <div class="themed_days_description" id="goscrol1">
            <div class="">
                <!----------------------------------------------------------------------------------->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Themed Days Description</h1>
                    
                </div>


                <!---------------------- change themed days description--------------------------------------------> 
       
        {% for key,value in form_day_description.items %}        
        <form method='POST' action="{% url 'adminPanel:editPackDescription' pack.id key %}">
            {% csrf_token %}
            <div class="contentalladd description_section">
                {{ value }}                                    
                <div id='current_place'>
                    <button type="submit" class="save button_inner"
                        style="max-width: 9.5%;
                                color:#fff;
                                "

                        >Save</button>
                
                </div>     
            </div>
        </form>
        {% endfor %}
        

    </div>
    <div class="text-center">
        <h1 class="h3 mb-0 text-gray-800 ">Edit Themed Pack Calendar</h1>
    </div>
    <div class="themed_price">
    <div class="themed_inner">
  

    <div class="text-center">
        <h1 class="h3 mb-0 text-gray-800">Price</h1>
    </div>
    
    <form method='POST' action="{% url 'adminPanel:priceEdit' pack.id %}#number_travelers">
        {% csrf_token %}
        {{ form_price }}
        <button type="submit" class="save button_inner"
        style="max-width: 9.5%;
       color:#fff"
        >Save</button>
    </form>

    </div>
    <div class="number_inner">
    <div class="text-center">
        <h1 class="h3 mb-0 text-gray-800">Number Of Travelers</h1>
    </div>
 
    <form method='POST' action="{% url 'adminPanel:quantityEdit' pack.id %}#number_travelers" id="number_travelers">
        {% csrf_token %}
        {{ form_quantity }}
        <button type="submit" class="save button_inner"
        style="max-width: 9.5%;
       color:#fff"
        >Save</button>
    </form>
</div>
</div>

                        <!----------------------END change themed pack---------------------------------------------> 

                        

                        
                    




                    

                        </div> <!-- 		End of Container -->

                                    </div>
        </div>
                 <!---------------------------------------------------------------------------------------->

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->
          
                    
            <script>
                
                $(document).ready(function () {
                    var calendar = $('#calendar').fullCalendar({
                        header: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'month,agendaWeek,agendaDay'
                        },
                        events: [
                        {% for day in calendar %}
        
                                {
                                    title: "Quantity: {{ day.quantity }} Price {{ day.calendar_price }}",
                                    start: '{{ day.date|date:"d/M/Y" }}',
                                    end: '',
                                    id: '',
                                    allDay: true,
                                },
                        {% endfor %}
                        ],
                        selectable: false,
                        selectHelper: false,
                        editable: false,
                        eventLimit: true,
                        eventAfterRender: function (event, element, view) {
                            var k=event.title.split(' ');
                    if (k[1] == 0) {
                        
                        //event.color = "#FFB347"; //Em andamento
                        element.css('background-color', 'rgb(255, 64, 31)');
                        
                    } 
                    else if(k[1] > 0){
                        element.css('background-color', 'rgb(66, 185, 4)');
                    }
                   k[0].split('\n');
                    console.log(k)
// alert('Number of breaks:  ' + numberOfLineBreaks);
                    // event.title[0].addClass('.first');
                    // console.log(k[0])
                    // k[0].setattribute('class', 'dkjajsl')
                //  let quentity= document.createElement('div');

                //  quentity.append(k[0]);
                //  quentity.setAttribute('class')
                //  element.find(".fc-title").append(quentity);
    //   element.find(".fc-title").append('<div class="some">    </div>');
    //   element.find(".fc-title").append('<div class="das">price' + k[1] + '</div>');
    //   $(".fc-title").children().append('dashjdks');
    //   console.log(  $(".fc-  title").children())
                    // element.find('.fc-title').append('<div class="quantity"> Quantity: ' + k[0] + '</div>'  );
                    // element.find('.quantity').append('<div class="das">price' + k[1] + '</div>')
                    
                },

                      
                    });
                });
        
            </script>
                <br/>
                <h2 align="center"><a href="#"></a></h2>
                <br/>
                <div class="container">
                    <div id="calendar"></div>
                </div>

                <script>
                     $(document).ready(function(){
  
  $("a").on('click', function(event) {
    if (this.hash !== "") {
      event.preventDefault();
      var hash = this.hash;
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 1800, function(){

        });
        } 
        });
    });

                </script>

               
{% endblock %}






templates/adminPanel/dashboardThemedTours/order_themed_packs.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

                <!-- Begin Page Content -->
                <div class="main_pack">
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Ordered Themed packs</h1>
                        <div class="add">
                            <a href="{% url 'adminPanel:addThemedPackOrder' %}">ORDER THEMED PACK</a>
                        </div>
                    </div>


                    <!-------------------ORDERED THEMED PACKS---------------------------> 


                    <table class="table " id= "table-id">

                        <div class="row">
                      <thead>
                          <tr>
                              <th style="width: 35px;">
                                  <input type="checkbox" class="checkAll" name="checkAll" />
                              </th>
                              <th class="AcomodationHeader">ORDERED THEMED PACK</th> 
                              <th ></th> 
                          </tr>
                      </thead>
                      {% for order in order_packs %}
                          <tbody >

                                  <tr>
                                      <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                        <td class=""><a href="{% url 'adminPanel:editThemedPackOrder' order.id %}">{{ order.pack }} | {{ order.user }}</a></td>
                                        <td><a href="{% url 'adminPanel:editThemedPackOrder' order.id %}">Edit</a></td>
                                        <td class="delete" > Delete Item </td>
                                  </tr>

                          </tbody>
                      {% endfor %}

                    </table>



                            <!---------------- END ORDERED THEMED PACKS----------------->

                </div>
                         <!-- 		End of Container -->


            

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->
{% endblock %}





































































          










         <!-- Footer -->
         <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; BookyTrip 2021</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->


<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.bundle.min.js"></script>


<!-- Custom scripts for all pages-->
<script src="/js/sb-admin-2.js"></script>
<script type="text/javascript">
    $('.confirmation').on('click', function () {
        return confirm('Are you sure to Delete?');
    });
</script>
</body>

</html>




