urls.py
from django.urls import path
from . import views

app_name = "adminPanel"


urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#adminpart url 
    path('dashboardcountry', views.dashboard_country, name='dashboardCountry'),
    path('deletecountry/<int:id>', views.delete_country, name='deleteCountry'),
    path('addcountry', views.add_country, name='addCountry'),
    path('dashboardcities/<int:id>', views.dashboard_city, name='dashboardCities'),
    path('dashboardcityadd', views.dashboard_city_add, name='dashboardCityAdd'),
    path('dashboardcitysingle/<int:id>', views.dashboard_city_single, name='dashboardCitySingle'),
    path('dashboardcitydelete/<int:id>', views.dashboard_city_delete, name='dashboardCityDelete'),

    path('dashboardfooter', views.dashboard_footer, name='dashboardFooter'),

    path('dashboardtermsandconditions', views.dashboard_terms_and_conditions, name='dashboardTermsAndConditions'),

    path('dasbhoardprivacypolicy', views.dashboard_privacy_policy, name='dashboardPrivacyPolicy'),

    path('packduration', views.dashboard_themed_pack_durations, name='packDuration'),
    path('addpackduration', views.dashboard_add_themed_pack_durations, name='AddpackDuration'),
    path('deletepackduration/<int:id>', views.delete_duration, name='deletePackDuration'),

    path('packvarieties', views.dashboard_pack_varieties, name='packVarieties'),
    path('packvarietiesadd', views.dashboard_add_pack_varieties, name='packVarietiesAdd'),
    path('deletevarieties/<int:id>', views.delete_variety, name='deleteVarieties'),

    path('dashboardcarmarks', views.dashboard_car_marks, name='dashboardCarMarks'),
    path('dashboardcarmarkadd', views.dashboard_car_mark_add, name='dashboardCarMarkAdd'),
    path('deletecarmark/<int:id>', views.delete_car_mark, name='deleteCarMark'),

    path('dashboarddefaultprice', views.dashboard_default_price, name='dashboardDefaultPrice'),
    path('dashboarddefaultpercentage', views.dashboard_default_percentage, name='dashboardDefaultPercentage'),
    path('dashboarddefaultpercentageadd', views.dashboard_default_percentage_add, name='dashboardDefaultPercentageAdd'),
    path('dashboarddefaultpercentageadd/<int:id>', views.dashboard_default_percentage_delete, name='dashboardDefaultPercentageDelete'),

    path('dashboardwhyus', views.dashboard_why_us, name='dashboardWhyUs'),
    path('dashboardwhyusadd', views.dashboard_why_us_add, name='dashboardWhyUsAdd'),
    path('dashboardwhyusedit/<int:id>', views.dashboard_why_us_edit, name='dashboardWhyUsEdit'),
#adminpart end

#user url

    path('admins', views.dashboard_admins, name='admins'),
    path('suppliers', views.dashboard_suppliers, name='suppliers'),
    path('customers', views.dashboard_customers, name='customers'),

    path('addadmin', views.dashboard_admin_add, name='addAdmin'),
    path('editadmin/<int:id>', views.dashboard_admin_edit, name="editAdmin"),
    path('editsupplier/<int:id>', views.dashboard_supplier_edit, name='editSupplier'),
    path('editcustomer/<int:id>', views.dashboard_customer_edit, name='editCustomer'),
    path('deleteadmin/<int:id>', views.delete_admin, name='deleteAdmin'),

#user end

#components

    path('dashboardfaq', views.dashboard_faq, name='dashboardFaq'),
    path('editfaq/<int:id>', views.faq_edit, name='editFaq'),
    path('deletefaq/<int:id>',views.faq_delete, name='deleteFaq'),
    path('addfaq',views.faq_add,name='addFaq'),

    path('homepagedestination', views.home_page_destination, name='homePageDestination'),

    path('interestingfacts', views.interesting_facts, name='interestingFacts'),
    path('editleftinterestingfact', views.edit_interesting_fact_left, name='editInterestingFactLeft'),
    path('editrightinteresingfact', views.edit_interesting_fact_right, name='editInterestingFactRight'),

    path('dashboardcontacts', views.dashboard_contacts, name='dashboardContacts'),
    path('dashboardcontact/<int:id>', views.dashboard_contact, name='dashboardContact'),

    path('dashboardabout', views.dashboard_about, name='dashboardAbout'),

#components end

    path('dashboardpacks', views.dashboard_themed_packs, name='dashboardPacks'),
    path('dashboardsinglepack/<int:id>', views.dashboard_single_pack, name='dashboardSinglePack'),
    path('editpack/<int:id>', views.edit_themed_pack, name='editPack'),
    path('editpackdescription/<int:id>/<int:findex>', views.edit_themed_pack_description, name='editPackDescription'),
    path('addpack', views.add_themed_pack, name='addPack'),
    path('addthemeddaysdescriptions/<int:id>', views.add_themed_days_descriptions, name='addThemedDaysDescriptions'),
    path('themedpackreservation/<int:id>', views.themed_pack_reservation, name='themedPackReservation'),

    path('priceedit/<int:id>', views.dashboard_price_edit, name='priceEdit'),
    path('quantityedit/<int:id>', views.dashboard_quantity_edit, name='quantityEdit'),

    path('themedpackreview', views.themed_pack_review, name='themedPackReview'),
    path('editthemedpackreview/<int:id>', views.edit_themed_pack_review, name='editThemedPackReview'),
    path('deletethemedpackreview/<int:id>', views.themed_pack_review_delete, name='deleteThemedPackReview'),

    path('themedpackorder', views.themed_pack_orders, name='themedPackOrder'),
    path('addthemedpackorder', views.themed_pack_order_add, name='addThemedPackOrder'),
    path('editthemedpackorder/<int:id>', views.themed_pack_order_edit, name='editThemedPackOrder'),

    path('dashboardapartment', views.dashboard_apartments, name='dashboardApartment'),
    path('dashboardapartmentsingle/<int:id>', views.dashboard_apartment_single, name='dashboardApartmentSingle'),
    path('dashboardaccommodationapartmentedit<int:id>', views.dashboard_accommodation_apartment_edit, name='dashboardAccommodationApartmentEdit'),
    path('dashboardapartmentedit<int:id>', views.dashboard_apartment_edit, name='dashboardApartmentEdit'),

    path('dashboardhotels', views.dashboard_hotels, name='dashboardHotels'),
    path('dashboardhotelsingle/<int:id>', views.dashboard_hotel_single, name='dashboardHotelSingle'),
    path('dashboardhoteledit<int:id>', views.dashboard_hotel_edit, name='dashboardHotelEdit'),
    path('dashboardhoteldelete/<int:id>', views.dashboard_hotel_delete, name='dashboardHotelDelete'),

    path('dashboardaccomodationadd', views.dashboard_accomodation_add, name='dashboardAccomodationAdd'),
    path('dashboardhoteladd/<int:id>', views.dashboard_hotel_add, name='dashboardHotelAdd'),
    path('dashboardhoteldescriptionadd/<int:id>', views.dashboard_hotel_description_add, name='dashboardHotelDescriptionAdd'),
    path('dashboardapartmentadd/<int:id>', views.dashboard_apartment_add, name='dashboardApartmentAdd'),


    path('accomodationreview', views.dashboard_accomodation_reviews, name='accomodationReview'),
    path('accomodationreviewedit/<int:id>', views.dashboard_accomodation_review_edit, name='accomodationReviewEdit'),

    path('carreview', views.dashboard_car_review, name='carReview'),
    path('carreviewedit/<int:id>', views.dashboard_car_review_edit, name='carReviewEdit'),
    path('carreviewdelete<int:id>', views.delete_car_review, name='carReviewDelete'),

    path('dashboardcars', views.dashboard_cars, name='dashboardCars'),
    path('dashboardcaradd', views.dashboard_car_add, name='dashboardCarAdd'),
    path('dashboardcaredit/<int:id>', views.dashboard_car_edit, name='dashboardCarEdit'),


]

templates/adminPanel/dashboardComponents/FAQ.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">FAQ</h1>
                        <div class="add">
                            <a href="{% url 'adminPanel:addFaq' %}">ADD FAQ</a>
                        </div>
                    </div>


                    <!-------------------FAQ---------------------------> 


                    <table class="table " id= "table-id">
                        <div class="row">
                      <thead>
                          <tr>
                              <th style="width: 35px;">
                                  <input type="checkbox" class="checkAll" name="checkAll" />
                              </th>
                              <th class="AcomodationHeader">FAQ</th> 
                              <th ></th> 
                              <th ></th> 
                            </tr>
   
                      </thead>
  
                      <tbody >
                            {% for faq in faqs %}
                                {% if faq.id in faq_notification_tuple %}
                              <tr>
                                  <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                    <td class="new_class"><a href="{% url 'adminPanel:editFaq' faq.id %}">{{ faq.get_question_type_display }} | {{ faq.user }}</a>
                                        <span class="new_inner" > NEW</span></td>
                                    
                                    <td> <a href="{% url 'adminPanel:editFaq' faq.id %}">Edit </a> </td>
                                    <td class="delete" > <a href="{% url 'adminPanel:deleteFaq' faq.id %}">Delete Items </a> </td>
                                    <td></td>
                              </tr>
                                {% else %}
                                <tr>
                                    <td class=""><input type="checkbox" name="item[]" value="1"></td>
                                      <td class=""><a href="{% url 'adminPanel:editFaq' faq.id %}">{{ faq.get_question_type_display }} | {{ faq.user }}</a></td>
                                      <td> <a href="{% url 'adminPanel:editFaq' faq.id %}">Edit </a> </td>
                                      <td class="delete confirmation" > <a href="{% url 'adminPanel:deleteFaq' faq.id %}">Delete Items </a> </td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                      </tbody>
                      </table>



                            <!---------------- END FAQ ----------------->

                        </div>       
                         <!-- 		End of Container -->

                </div>
            

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->
{% endblock %}





templates/adminPanel/dashboardComponents/addfaq.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
{% load i18n %}
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Add FAQ</h1>
                        <!-- <div class="add">
                            <a href="#"></a>
                        </div> -->
                    </div>



                    <!-------------------------------ADD FAQ ------------------------> 

            <form action="{% url 'adminPanel:addFaq' %}" method="POST">
                {% csrf_token %}
                <div class="contentalladd">
                        <table>
                            <thead>
                                <tr>
                                    <div class="row align-items-center change_username">
                                        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                            <label for="question" class="col-form-label">question:</label>
                                        </div>
                                        <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10">
                                            <div class="form-floating">
                                                <textarea  id="question" class="form-control" placeholder="" name="question" style="height: 100px"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                            </thead>
                        </table>
    
    
                        <table>
                            <thead>
                                <tr>
                                    <div class="row align-items-center change_username">
                                        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-12">
                                            <label for="questiontype" class="col-form-label">question type:</label>
                                        </div>
                                        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-10">
                                            <select id="questiontype" class="form-select form-control" name="question_type">
                                                <option value="1">{% trans 'Pre-Sale Questions' %}</option>
                                                <option value="2">{% trans 'Other Type Questions' %}</option>
                                            </select>
                                        </div>
                                    </div>
                                </tr>
                            </thead>
                        </table>
    
    
    
                        <table>
                            <thead>
                                <tr>
    
                                    <!--------- answer --------->
                                    <div class="row align-items-center answer">
                                        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                        <label for="answer" class="col-form-label">answer:</label>
                                        </div>
                                        <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10">
                                            <div class="form-floating">
                                                <textarea id="answer" class="form-control" placeholder="" style="height: 100px" name="answer"></textarea>
                                              </div>
                                        </div>
                                    </div>
                                </tr>
                            </thead>
                        </table>
    
    
    
                        <div class="change_faqckack">
                            <table>
                                <thead>
                                    <tr>
                                        <div class="form-check checkbox">
                                            <input class="form-check-input" type="checkbox" id="permition" name="permition" >
                                            <label class="form-check-label" for="permition">Display on front-end</label>
                                        </div>
    
                                    </tr>   
                                </thead>
                            </table>
                        </div>
    
    
                        <div class="row  save_Delete">
                            
                            <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>
                   
                          <!-- <button type="button" class="Delete2 col-xl-2 col-lg-3 col-md-3 col-sm-4 ">Delete</button> -->
                        
                      </div>
                </div>
            </form>

            <!-------------------------------AND ADD FAQ ------------------------> 
                    






                        </div> <!-- 		End of Container -->

                                    </div>
                 <!---------------------------------------------------------------------------------------->

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}





templates/adminPanel/dashboardComponents/changeFAQ.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
{% load i18n %}
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Change faq</h1>
                    </div>



                    <!-------------------------------CHANGE FAQ --------------> 

            <form action="{% url 'adminPanel:editFaq' faq.id %}" method="POST">
                {% csrf_token %}
                <div class="contentalladd">
                    <table>
                        <thead>
                            <tr>
                                <div class="row align-items-center change_username">
                                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                        <label for="question" class="col-form-label">question:</label>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10">
                                        <div class="form-floating">
                                            <textarea  id="question" class="form-control" placeholder="Here is your question" name="question" style="height: 100px">{{ faq.question }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </tr>
                        </thead>
                    </table>


                    <table>
                        <thead>
                            <tr>
                                <div class="row align-items-center change_username">
                                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-12">
                                        <label for="questiontype" class="col-form-label">question type:</label>
                                    </div>
                                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-10">
                                        <select name="question_type" class="selectpicker form-control "id="">
                                            <option selected hidden value="{{ faq.question_type }}">{{ faq.get_question_type_display }}</option>
                                            <option value="1">{% trans 'Pre-Sale Questions' %}</option>
                                            <option value="2">{% trans 'Other Type Questions' %}</option>
                                        </select>
                                    </div>
                                </div>
                            </tr>
                        </thead>
                    </table>



                    <table>
                        <thead>
                            <tr>

                                <!--------- answer --------->
                                <div class="row align-items-center answer">
                                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                    <label for="answer" class="col-form-label">answer:</label>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10">
                                        <div class="form-floating">
                                            <textarea id="answer" class="form-control" placeholder="This is your answer" style="height: 100px" name="answer">{{ faq.answer }}</textarea>
                                          </div>
                                    </div>
                                </div>
                            </tr>
                        </thead>
                    </table>



                    <div class="change_faqckack">
                        <table>
                            <thead>
                                <tr>
                                    <div class="form-check checkbox">
                                        <input class="form-check-input" type="checkbox" id="permition" name="permition" >
                                        <label class="form-check-label" for="permition">Display on front-end</label>
                                    </div>


                                </tr>   
                            </thead>
                        </table>
                    </div>


                    <div class="row  save_Delete">
                            
                        <button type="submit" class="save button_inner ">SAVE</button>
                    
                  </div>
                </div>
            </form>



                        <!---------------------------------- AND CHANGE FAQ ------------------> 
                    






                        </div> <!-- 		End of Container -->

                                    </div>
                 <!---------------------------------------------------------------------------------------->

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}






templates/adminPanel/dashboardComponents/dashboard_about.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <style>
        table#add {
            width: 68%;
        }
    </style>
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Why Us</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardAbout' %}" enctype="multipart/form-data"> 
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

templates/adminPanel/dashboardComponents/dashboard_contact_inner.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Contacts</h1>
        </div>
       


<div class="row align-items-center change_username">
    <div class="col-xl-5 col-lg-5 col-md-10 col-sm-10">
        <div class="content title">
            <h5>Name Surname:</h5>                                    
            <p>{{ contact.name }}  {{ contact.surname }}</p>
        </div>
        <hr>
        
        <div class="content gmail">
            <h5>Email:</h5>
            <p>  {{ contact.email }}</p>
        </div>
        <hr>
    </div>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-10">
    <div class="Description">
        <h5>Message:</h5>
        <p> {{ contact.text }}</p>
    </div>
    </div>
</div>


</div>
</div>

{% endblock %}

templates/adminPanel/dashboardComponents/dashboard_contacts.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Contacts</h1>
        </div>
        <table class="table " id= "table-id">
            <div class="row">
          <thead>
              <tr>
                  <th style="width: 35px;">
                      <input type="checkbox" class="checkAll" name="checkAll" />
                  </th>
                  <th class="AcomodationHeader">Name Surname</th> 
                  <th >Email</th> 
                  <th >Message</th> 
                  <th >Date</th> 
                  <th ></th> 
                </tr>

          </thead>
{% for contact in contacts %}
    <tr>
        <td class=""><input type="checkbox" name="item[]" value="1"></td>
        <td class="new_class"><a href="{% url 'adminPanel:dashboardContact' contact.id %}">{{ contact.name }}  {{ contact.surname }}</a>
            <!-- <span class="" style="font-weight: bold; color: red;"> NEW</span> -->
        </td>
        <td>{{ contact.email }}</td>
        <td> <a href="">{{ contact.text }} </a> </td>
        <td> <a href="">{{ contact.send_time }} </a> </td>
        <td class="delete" > <a href="">Delete Items </a> </td>
        <td></td>
    </tr>

{% endfor %}
</div>
</table>
</div>
</div>
</div>

{% endblock %}

templates/adminPanel/dashboardComponents/home_page_destination.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Home Page Destination</h1>
                    </div>

                   
                    <form action="{% url 'adminPanel:homePageDestination' %}" method="POST" enctype="multipart/form-data">
                        
                    {% csrf_token %}

                     
                    <table class="table destination_page" id="" >
                        
                            <tr>
                                
                              
                                <td >        
                                    {{ form.title.label }} <span style="color: grey;">(max length: 20)</span>                          
                                    {{ form.title }}

                                    {{ form.text.label }}   <span>(max length: 330)</span>                           
                                    {{ form.text }}

                                    {{ form.video.label }}                          
                                    {{ form.video }}

                                 </td>                             
                               
                            </tr>
                            
                     </table>
                     
                    <div class="row  save_Delete">

                        <button type="submit" class="save button_inner ">SAVE</button>
                    
                    </div>
                     
                    </form>

        
                  
                        </div> <!-- 		End of Container -->

                                    </div>
                 

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

 {% endblock %}

templates/adminPanel/dashboardComponents/interesting_facts.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}

<div class="main_pack">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">INTERESTING FACTS</h1>
        </div>
   
      <div class="intereseting_facts">  
          
        <div class="interesting_facts_inner">
          <form action="{% url 'adminPanel:editInterestingFactLeft' %}" method='POST' enctype="multipart/form-data">  
            {% csrf_token %}
            <div class="heading_facts">
                <label for="heading_first">Header</label>
                {{ left_form.title }}                
            </div>
            <div class="image_facts">
              <div class="fact_image_show">
                <img src="{{ left_fact.image.url }}" alt="">
              </div>
                <label for="image_file">Image <span>(Image Size Must Be 350px/525px)</span>    </label> 
                {{ left_form.image }}
            </div>
            <div class="heading_textarea">
                <label for="description_first">Description (Max 50 char)</label>
                {{ left_form.text }}
            </div>
            <div class="row  save_Delete">                            
              <button type="submit" class="save button_inner ">SAVE</button>      
            </div>
            </form>
        </div>
       
      
        
        <div class="interesting_facts_inner">
          <form action="{% url 'adminPanel:editInterestingFactLeft' %}" method="POST"  id="form_save" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="heading_facts">
                <label for="heading_second">Header</label>
                {{ right_form.title }}   
            </div>
            <div class="image_facts">
                <div class="fact_image_show">
                  <img src="{{ right_fact.image.url }}" alt="">
                </div>
                <label for="image_file">Image <span>(Image Size Must Be 350px/525px)</span></label> 
                {{ right_form.image }}
              
            </div>
            <div class="heading_textarea">
                <label for="description_second">Description <span>(Max 50 char)</span> </label>
                {{ right_form.text }}
            </div>
            <div class="row  save_Delete">                            
              <button type="submit" class="save button_inner ">SAVE</button>     
              <div id="output" class="ajax_response"></div> 
            </div>
          </form>
        </div>
       <!-- Trigger the modal with a button -->
       <div id="error_message" class="ajax_response" style="float:left"></div>
    

<!-- Modal -->

</div>
      
      </div>


  </div>
</div>

{% endblock %}